openapi: 3.0.3
info:
  title: Accounting Service v1
  description: |-
    API for Accounting Service
  termsOfService: http://swagger.io/terms/
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
components:
  schemas:
    OpenPatientAccountCommand:
      type: object
      properties:
        prescriptionId:
          type: string
        patientId:
          type: integer
    ClosePatientAccountCommand:
      type: object
      properties:
        prescriptionId:
          type: string
        patientId:
          type: integer
        accountId:
          type: integer
    PatientAccountCreatedEvent:
      type: object
      properties:
        prescriptionId:
          type: string
        patientId:
          type: integer
        accountCreated:
          type: boolean
        accountId:
          type: integer
        error:
          type: string
    PatientAccountTerminatedEvent:
      type: object
      properties:
        prescriptionId:
          type: string
        patientId:
          type: integer
        accountId:
          type: integer